### ISSUE TITLE
Project is too slow

### ISSUE THREAD

**Issue by neptuneresearch** [Mitchellpkt/chess#18]
Actually the code frequency graph is hilarious, the work rate on this project has linearly declined since it was created :rofl: 

![tooslow](https://user-images.githubusercontent.com/39543276/41427006-80310904-6fd3-11e8-94f5-e387938e217d.png)

**Comment by Mitchellpkt** [comment]
@neptuneresearch, this scales with O(M^2+N^3) where M is the number of moves in, and N is the number of pieces remaining on the board. Will speed up soon.

**Comment by neptuneresearch** [comment]
:+1:
